### ISSUE TITLE
Bump to 2.39, please.

### ISSUE THREAD

**Issue by jorgicio** [Frogging-Family/glibc-eac#10]
Hi.
2.39 was just released, but DT_HASH was removed since 2.38 that allegedly affect some games. Also, the rogue company patch doesn't work here.

Thanks in advance.

**Comment by ptr1337** [comment]
> allegedly

According valve the DT_HASH patchset is not required anymore.

**Comment by ptr1337** [comment]
Rogue Company should be also first retested with 2.39, before rebasing the patchset against it

**Comment by jorgicio** [comment]
> > allegedly
> 
> According valve the DT_HASH patchset is not required anymore.

Yes, but that broke some games like Insurgency Sandstorm.

**Comment by GenocideStomper** [comment]
At least Back 4 Blood, Insurgency: Sandstorm and Squad don't work currently.

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/glibc-eac/commit/7bef4f36fac61d456b11e611e39d748f42fee0d8
