### ISSUE TITLE
failed to install need manual intervention 

### ISSUE THREAD

**Issue by Tune45** [Frogging-Family/glibc-eac#11]
My OS is endeavouros
`<command-line>: error: "_FORTIFY_SOURCE" redefined [-Werror]
<command-line>: note: this is the location of the previous definition
cc1: all warnings being treated as errors
make[2]: *** [../o-iterator.mk:9: /home/tuner/.cache/yay/glibc-eac/src/glibc-build/stdlib/testmb.o] Error 1
make[2]: Leaving directory '/home/tuner/.cache/yay/glibc-eac/src/glibc/stdlib'
make[1]: *** [Makefile:484: stdlib/tests] Error 2
make[1]: Leaving directory '/home/tuner/.cache/yay/glibc-eac/src/glibc'
make: *** [Makefile:9: check] Error 2
==> ERROR: A failure occurred in check().
    Aborting...
 -> error making: glibc-eac-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
glibc-eac - exit status 4
`

**Comment by Tk-Glitch** [comment]
This was the result of one of the patches failing and was fixed a while ago. Closing.
