### ISSUE TITLE
Breaks CS2 and Dota

### ISSUE THREAD

**Issue by MaKaNu** [Frogging-Family/glibc-eac#14]
Both Games crashes if glibc-eac 39_1 is installed. If I install repos glibc version it runs fine.

**Comment by Tk-Glitch** [comment]
You need to update to 2.39+r52
https://github.com/Frogging-Family/glibc-eac/actions/runs/9128095372

**Comment by MaKaNu** [comment]
is the arch package on that release?

**Comment by Tk-Glitch** [comment]
Yep!
https://archlinux.org/packages/core/x86_64/glibc/

**Comment by Tk-Glitch** [comment]
I have updated the release page with the new packages.
https://github.com/Frogging-Family/glibc-eac/releases/tag/release_1
