### ISSUE TITLE
Cannot build package, failure occurred in check()

### ISSUE THREAD

**Issue by xiota** [Frogging-Family/glibc-eac#2]
I cannot build the package.  Running Endeavor OS with distro-specific repositories and packages removed.  Ran `pacman -Syu` before `makepkg`.  I get this error:
```
...
FAIL: nss/tst-nss-files-hosts-long
UNSUPPORTED: posix/tst-cet-vfork-1
UNSUPPORTED: stdlib/tst-secure-getenv
FAIL: stdlib/tst-system
...
Summary of test results:
      2 FAIL
   5073 PASS
     89 UNSUPPORTED
     14 XFAIL
      8 XPASS
make[1]: *** [Makefile:647: tests] Error 1
make[1]: Leaving directory '.../glibc-eac/src/glibc'
make: *** [Makefile:9: check] Error 2
==> ERROR: A failure occurred in check().
    Aborting...
```

**Comment by Tk-Glitch** [comment]
Did you run `makepkg` alone? Try `makepkg -s` to make sure you grab dependencies.

**Comment by xiota** [comment]
I ran `makepkg` without any flags.  If there are missing dependencies, it usually quits at the beginning with a list.  I tried with `makepkg -s`, and it doesn't seem to behave any differently when the dependencies are already installed.

It looks like compilation itself is successful, but the errors are at the end when it tries to runs tests.  With the latest git changes (with rogue gallery patch), I get the following errors (I cut out most of the XPASS and UNSUPPORTED lines to show the fails):
```
...
UNSUPPORTED: nptl/test-rwlockattr-printers
FAIL: nss/tst-nss-files-hosts-long
UNSUPPORTED: posix/tst-cet-vfork-1
FAIL: stdlib/tst-arc4random-fork
UNSUPPORTED: stdlib/tst-secure-getenv
FAIL: stdlib/tst-system
UNSUPPORTED: string/tst-memchr-rtm
...
Summary of test results:
      3 FAIL
   5073 PASS
     89 UNSUPPORTED
     14 XFAIL
      8 XPASS
make[1]: *** [Makefile:653: tests] Error 1
make[1]: Leaving directory '.../glibc-eac/src/glibc'
make: *** [Makefile:9: check] Error 2
==> ERROR: A failure occurred in check().
    Aborting...
```

**Comment by Tk-Glitch** [comment]
I cannot reproduce the issue on my end. I disabled two tests that were failing for me (see https://github.com/Frogging-Family/glibc-eac/blob/main/PKGBUILD#L172 ) but those are passing just fine here.

After searching for a bit, it seems those tests will usually fail when you don't have enough installed/free RAM. The machine I used has 32GiB installed, and had ~30GiB free when I launched the compilation. If you have less RAM on your end it might be the issue.

If you want to forcefully go through, you can comment https://github.com/Frogging-Family/glibc-eac/blob/ac20a46d1bcbdf96ea2aefad01f7641ca5b1e946/PKGBUILD#L176 out (by adding a `#` at the beginning of that line) before rebuilding, which will skip the checks altogether.

**Comment by xiota** [comment]
The packages are created successfully with `makepkg --nocheck`.  I do wonder if there are some hidden dependencies for those tests because this is a relatively recently installed system, and I don't normally consider 16G to be RAM starved.

**Comment by Tk-Glitch** [comment]
The CI hit different failures (https://github.com/Frogging-Family/glibc-eac/actions/runs/2818395858):
```
2022-08-08T15:21:56.3181164Z FAIL: io/tst-close_range
2022-08-08T15:21:56.3184681Z FAIL: misc/tst-personality)
```
It seems to be almost random :D I was also able to reproduce the initial failures I hit on the plain untouched Arch package so it doesn't seem to be linked to the reverts. Arch maintainer apparently also hit some similar weirdness so I guess disabling the checks is acceptable.
