### ISSUE TITLE
Causes video capture device to stop functioning

### ISSUE THREAD

**Issue by moeraccoon** [Frogging-Family/glibc-eac#3]
So, I installed the packages through this:
```
wget https://github.com/Frogging-Family/glibc-eac/releases/download/test/lib32-glibc-2.36-1-x86_64.pkg.tar.zst
wget https://github.com/Frogging-Family/glibc-eac/releases/download/test/glibc-2.36-1-x86_64.pkg.tar.zst
sudo pacman -U glibc-2.36-1-x86_64.pkg.tar.zst lib32-glibc-2.36-1-x86_64.pkg.tar.zst
```

It fixed my issue with EAC, but after doing this a new problem showed up. 
I don't have many expectations of having this solved, but maybe there's something obvious to others that isn't obvious to me because I'm not the most knowledgeable.

I have a blackmagic device, intensity pro 4K. I got it running installing the drivers from aur:
https://aur.archlinux.org/packages/decklink

As per the pinned comment on the aur page I enabled DesktopVideoHelper.service

It worked, I've been using it for almost a year. At some point I updated some stuff, the service didn't start on boot anymore, so I just re enabled it, all back to normal.

After installing this version of glibc and lib32-glibc the capture card stopped working. When I open OBS if I try to add it back it's not even an option, which is the same thing that happened when DesktopVideoHelper.service wasn't on.

Again, I don't expect much to come out of this, I momentarily just downgraded my system as a whole editing pacman.conf and running Syyuu, but if I could get to keep my system update and have everything working it would be sweet.

**Comment by Tk-Glitch** [comment]
Does it work with regular glibc 2.36?

**Comment by moeraccoon** [comment]
I do believe so, but I'll double check to be safe.

**Comment by moeraccoon** [comment]
Well, a bit odd, but after updating again and reapplying the versions you provided the video capture seems to work.

I apologize for wasting time.

Love the profile picture btw. Froppy is best girl.

**Comment by Tk-Glitch** [comment]
I didn't expect the issue to fix itself, but I also found it weird considering we're only restoring functionality and not removing some. I'm glad it all worked out in the end.

Thanks for the frog love also :frog:
