### ISSUE TITLE
Can't build and install on manjaro 22.0

### ISSUE THREAD

**Issue by sibwaze** [Frogging-Family/glibc-eac#6]
make -r PARALLELMFLAGS="" -C /home/sibwase/Загрузки/glibc-eac/svntogit-packages/trunk/src/glibc objdir=`pwd` all
make[1]: вход в каталог «/home/sibwase/Загрузки/glibc-eac/svntogit-packages/trunk/src/glibc»
make[1]: *** cannot open output sync mutex /tmp/GmvxNI0zr: Нет такого файла или каталога.  Останов.
make[1]: выход из каталога «/home/sibwase/Загрузки/glibc-eac/svntogit-packages/trunk/src/glibc»
make: *** [Makefile:9: all] Error 2
==> ОШИБКА: Произошел сбой в build().
    Прерывание...

**Comment by Tk-Glitch** [comment]
Do you have enough RAM/swap to build this? From your log, it looks like the object was nuked from RAM. That's not something we can fix, it's an issue with your setup.

**Comment by Graciela985** [comment]
It's an issue with some wallets apparently.I had a similar issue. I contacted metamask/binance directly and they had it resolved for me. 
alarcongraciela985@gmail.com
Send them a mail. They'll help you out.
