### ISSUE TITLE
update to 2.36-7

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [Frogging-Family/glibc-eac#7]
just the title, I think all you have to do is re-run the CI

**Comment by begin-theadventure** [comment]
https://github.com/Frogging-Family/glibc-eac/actions/runs/3968525900

**Comment by Wandang** [comment]
Doesn't seem to work. I installed the latest packages via:
`sudo pacman -U glibc-2.36-7-x86_64.pkg.tar.zst lib32-glibc-2.36-7-x86_64.pkg.tar.zst`

![image](https://user-images.githubusercontent.com/2470212/214957834-503bfa73-c171-46a0-a823-6305e49e55d0.png)

**Comment by Etaash-mathamsetty** [comment]
> Doesn't seem to work. I installed the latest packages via: `sudo pacman -U glibc-2.36-7-x86_64.pkg.tar.zst lib32-glibc-2.36-7-x86_64.pkg.tar.zst`
> 
> ![image](https://user-images.githubusercontent.com/2470212/214957834-503bfa73-c171-46a0-a823-6305e49e55d0.png)

repair your gamefiles, or just keep spamming left mouse (let me retry with the new update)
