### ISSUE TITLE
Mirror changed from Github to Gitlab

### ISSUE THREAD

**Issue by jorgicio** [Frogging-Family/glibc-eac#8]
Hi!

Around a month ago, Arch repos are merged from Github to Gitlab, and a recent version of Glibc, 2.38, was released. So the glibc_eac.sh script should be updated to the new git mirror. The URL is https://gitlab.archlinux.org/archlinux/packaging/packages.

Thanks!

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/glibc-eac/commit/5abfa28eac43e5c768893c789b03edf6b8915586
