### ISSUE TITLE
Update to 2.38-4

### ISSUE THREAD

**Issue by jorgicio** [Frogging-Family/glibc-eac#9]
Hi.

Today the 2.38-4 was just released, however when I try to apply the rogue_company patch manually (by editing the PKGBUILD instead to run the glibc_eac.sh script and then doing the `makepkg -si`), the patch fails due to changes between the new and the previous release of glibc.

Thanks.

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/glibc-eac/commit/84bc7bf2cddd0134b34bb6b05b6e6eb946b2e473
